random_example = 54
no_ite = true

[expr_search]
sample = 64
dag_size = true
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = true
filter = { deductive_combine = true, deductive_reverse = true } 