
random_example = 10
limited_ite = true
smt_solver = "z3"

[expr_search]
sample = 64
dag_size = true
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = true
filter = { deductive_combine = true, deductive_reverse = true } 

 