random_example = 54
limited_ite = true
chatgpt = true

[expr_search]
sample = 64
dag_size = false
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = false
filter = { deductive_combine = true, deductive_reverse = true } 
