random_example = 10
no_ite = true
# chatgpt = 

[expr_search]
sample = 64
dag_size = true
filter = { deductive_combine = false, deductive_reverse = false } 

[improve_search]
sample = 8
dag_size = true
filter = { deductive_combine = false, deductive_reverse = false } 