random_example = 1
no_ite = true
# chatgpt = false

[expr_search]
sample = 64
dag_size = false
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = false
filter = { deductive_combine = true, deductive_reverse = true } 
