[package]
name = "dryadsynth"
version = "0.1.0"
build = "build.rs"
edition = "2024"

[dependencies]
libc = "0.2"


[build-dependencies]
flate2 = "1.1.0"
glob = "0.3.2"
reqwest = { version = "0.12.15", features = ["blocking"] }
serde_json = "1.0.140"
tar = "0.4.44"
zip-extract = "0.2.1"
