random_example = 1
ite_tree_limit = 100000

[cond_search.filter]
time_limit = 500

[expr_search]
sample = 8
dag_size = true
# atom_diversity_order = true
# mem_size_limit = 5
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = true
# atom_diversity_order = true
# mem_size_limit = 5
filter = { deductive_combine = true, deductive_reverse = true }