[package]
name = "dryadsynth_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
capnp = "0.18"
sygus-parser = "0.1"
libc = "0.2"

[build-dependencies]
capnpc = "0.18"

[lib]
crate-type = ["cdylib", "rlib"]
