random_example = 50
limited_ite = true
gpt_version = "gpt-4"

[expr_search]
sample = 64
dag_size = true
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = true
filter = { deductive_combine = true, deductive_reverse = true } 