random_example = 10
limited_ite = true
chatgpt = false

[expr_search]
sample = 64
dag_size = false
mem_size_limit = 300
filter = { deductive_combine = false, deductive_reverse = false } 

[improve_search]
sample = 8
dag_size = false
mem_size_limit = 300
filter = { deductive_combine = false, deductive_reverse = false } 