random_example = 1
ite_tree_limit = 100000

[expr_search]
sample = 8
dag_size = false
# atom_diversity_order = true
# mem_size_limit = 5
filter = { deductive_combine = true, deductive_reverse = true } 

[improve_search]
sample = 8
dag_size = false
filter = { deductive_combine = true, deductive_reverse = true } 
# atom_diversity_order = true
# mem_size_limit = 5
# filter = { deductive_combine = true, deductive_reverse = true }